---
title: "Criteria for evaluation"
bibliography: ../assets/references.bib
csl: ../assets/apa.csl
nocite: |
  @JOSSReviewCriteria
---

Bachelor's and Master's theses are evaluated according to the same criteria.
Once the **formal requirements** are met, the **main criteria** related to the process, the contribution, and the discussion are used to grade a thesis.

A [changelog](https://github.com/fs-ise/theses/commits/main/docs/criteria.md){target=_blank} is available for this document.

## Formal requirements

- A Bachelor's thesis should cover 30-50 pages (roughly 8,000 - 16,000 words), while a Master's thesis should cover 40-70 pages (roughly 12,000 - 28,000 words).
  Design-oriented, analytical, and quantitative theses are typically shorter than qualitative and literature-based ones.
  For a Master's thesis, a presentation is required, and a more substantial contribution is expected in line with the higher number of ECTS credits earned.
- Written in proper academic English, with a clear structure (paragraphs) and line of argument.
- Follows [citation practices](https://fs-ise.github.io/handbook/research/writing_technical.html#citations-and-reference-sections){target=_blank},
  using [APA format](https://apastyle.apa.org/style-grammar-guidelines/references/examples){target=_blank}, and refers primarily to peer-reviewed academic papers.
- Includes a title page, table of contents, abstract, common sections (e.g., IMRAD), a reference section, and appendices if applicable (a list of figures or tables is not required).
- Makes appropriate use of tables and figures, citing each table or figure in the text.
- Provides clear definitions for key terms.

## Main criteria

The **process** is evaluated according to the following criteria:

- **Systematicity** in managing time, resources, and challenges.
  Start early to have enough time for each task, ensure that resources such as labs, equipment, participants, partners, or thesis advisors are available at the right time, and reduce potential risks by anticipating them and identifying potential alternatives.
- **Proactiveness** in developing the topic (research question, theory, method, etc.) and incorporating feedback.
  To receive feedback, you can share (parts of) the thesis with us. We encourage you to challenge our feedback and suggest better alternatives.
- **Proficiency** in leveraging prior research, i.e., identifying relevant papers, achieving an appropriate understanding, assessing contributions critically, and organizing prior work in a persuasive way to clarify how the thesis builds on prior work and how it goes beyond prior work.

The **contribution** is evaluated based on several dimensions [based on @Leidner2020]:

- **Explicitness and significance of research objective or question**: Explain how your work builds on prior research, identify related contributions, and clarify the research gap you address.
  Readers should understand why your research promises interesting insights and who would benefit from it. The editorial of @LangePfarrer2017 provides useful suggestions to accomplish this.
- **Uniqueness in framing prior research**: In summarizing prior research, it is essential to organize existing contributions from the perspective of your work.
  Prior research, in itself, does not follow a predefined order. It is your responsibility to make sense of the literature and to adopt an organizing frame that helps readers understand how prior research relates to your contribution.
- **Systematicity of method**: Evaluation criteria and reporting guidelines depend on the method applied.
  A selection is provided below. In addition to reporting the methodological steps, *data and code should be made available* with the thesis according to standards of reproducible research.
  Corresponding methods papers can be found [here](writing/research.html), and requirements should be discussed with the thesis advisor.
- **Originality of theory**: Applies if your contribution involves a theoretical contribution, e.g., in the form of propositions, constructs, or models.
  Clarify how it differs from related theory and explain why it offers a plausible and more compelling perspective or explanation.
- **Interpretation and novelty of findings**: The findings should be interpreted appropriately, using a neutral tone, and avoiding overstating or understating their significance.
  Clearly distinguish findings that confirm prior research or common expectations. Effectively communicate the findings that are novel, interesting, or counterintuitive.

Recommended criteria and reporting guidelines for selected research methods (the [equator network](https://www.equator-network.org/){target=_blank} provides a comprehensive overview).
Additional guidelines can be provided upon request.

<!--
TBD: methodological coherence/fit?

Weights: We apply flexible weights because the topic of a thesis may limit the degree to which students' contributions can excel in any of the contribution dimensions.
-->

The contribution should be **discussed** with reference to

- The (methodological) limitations
- The implications for future research (research gaps)
- The implications for practice [@AgerfalkKarlsson2020].

::: {.callout-note title="Note on student ownership and feedback"}
Students are expected to critically engage with feedback provided by thesis advisors while accomplishing the contribution on their own.
Especially for top grades (1.0–1.7), simply implementing suggestions is not sufficient.
Instead, students are expected to maintain ownership of their work by applying independent judgment and, where appropriate, going beyond or critically reflecting on feedback from thesis advisors.
:::

## Presentation

A presentation is required for Master's theses. A presentation takes 15-20 minutes with 10 minutes of discussion.
It is evaluated based on the following criteria:

- The introductory section should convey why the topic is interesting, and it should be easy to follow for a general audience.
- The main section should demonstrate the objective, method, main findings, and contribution, giving experts the possibility to critically assess the different parts.
- The concluding section should give an outlook and briefly outline the implications.
- Presentation style and slides should be appropriate, i.e., displaying a clear structure, using academic terminology, providing references, connecting with the audience,
  taking approximately 2-3 minutes per slide, using short bullet-point summaries instead of longer paragraphs, and including illustrations rather than animations.
- Questions should be handled constructively, demonstrating in-depth knowledge of the thesis and familiarity with the broader topic area.

In line with the applicable regulations, the presentation receives a weight of 33% for students of Information Systems.
For students from other departments and degree programs (such as [IBWL](https://www.uni-bamberg.de/abt-studium/aufgaben/pruefungs-studienordnungen/masterstudiengaenge/internationale-betriebswirtschaftslehre/){target=_blank}), the presentation may not be graded.

<!-- 
https://www.uni-bamberg.de/psi/teaching/psi-teaching-posters/
https://www.dmm.bwl.uni-muenchen.de/download/info/dmm_formalia_2022_de.docx
-->

## Applicable regulations

<!-- 
- Bachelor Business Information Systems
- Bachelor International Information Systems Management
- Bachelor Angewandte Informatik
- Bachelor Software Systems Science
- Master Business Information Systems
- Master International Information Systems Management
- Master Angewandte Informatik
- Master Software Systems Science
- Master Computing in the Humanities
 -->

- [Prüfungs- und Studienordnungen](https://www.uni-bamberg.de/abt-studium/aufgaben/pruefungs-studienordnungen/){target=_blank}, insbes. Modulhandbücher
