---
title: "Hall of Fame"
---

On this page, we celebrate the accomplishments of our students 🎉 🍾 🎈

<!-- ## Publication of datasets -->

## 🏆 Awards

- Best Theory Paper Award, **Richard Schuster**, Gerit Wagner, and Guido Schryen. Received at the 39th International Conference on Information Systems (2018), San Francisco, California/USA, 2018.
- Christa Lindner Prize 2018: Richard Schuster.
- Christa Lindner Prize 2017: Julian Prester.

## 📒 Publications

<div class="references">
  <p><strong>Geßler, A., Schnickmann, K.</strong>, and Wagner, G. (2026). "Advancing literature review automation through API-based searches: Design of an independent emulator". Conditionally accepted: <em>Proceedings of the International Conference on Information Systems</em>.</p>
  <p><strong>Eckhardt, P., Ernst, K., Fleischmann, T., Geßler, A., Schnickmann, K., Thurner, L.</strong>, and Wagner, G. (2025). "<a href="https://doi.org/10.21105/joss.08775" target="_blank">search-query: An open source Python library for academic search queries</a>". <em>Journal of Open Source Software</em>, 11(118), 8775.</p>
  <p><strong>Prester, J.</strong>, Wagner, G., Hassan, N. R., and Schryen, G. (2021). “<a href="https://doi.org/10.1016/j.dss.2020.113432" target="_blank">Classifying the ideational impact of Information Systems Review Articles: A content-enriched deep learning approach</a>”. <em>Decision Support Systems</em> (DSS), 140, 113432.</p>
  <p><strong>Schuster, R.</strong>, Wagner, G., and Schryen, G. (2018). “<a href="https://aisel.aisnet.org/icis2018/design/Presentations/3/" target="_blank">Information Systems Design Science Research and cumulative knowledge development: An exploratory study</a>,” in <em>Proceedings of the 39th International Conference on Information Systems (ICIS 2018)</em>, San Francisco, California, USA</p>
  <p>Wagner, G., <strong>Empl, P.</strong>, and Schryen, G. (2020). “<a href="https://aisel.aisnet.org/ecis2020_rp/44/" target="_blank">Designing a novel strategy for reading and skimming literature corpora</a>,” in <em>Proceedings of the 28tℎ European Conference on Information Systems (ECIS 2020)</em>, Marrakech, Morocco.</p>
</div>

## 💽 Software

- [search-query](https://github.com/CoLRev-Environment/search-query){target=_blank} : Katharina Ernst, Peter Eckhardt, Thomas Fleischmann, Anna Geßler, Karl Schnickmann
- [deep-cenic](https://github.com/julianprester/deep-cenic){target=_blank} : Julian Prester
- [enlit](https://github.com/geritwagner/enlit){target=_blank} : Philip Empl
